### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by JerryBian** [JerryBian/quoll#5]
A list of potential supported features.

- [x] Ignore current folders if `from-file` specified
- [x] If neither `-n` nor `-s` specified, default to delete all files
- [ ] `Ctrl+C` support 
- [x] Support new option `--folder` name filters
- [x] Support new option `remove-empty-dir` to remove empty directories
